# Generated by Django 3.2.20 on 2023-09-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trainer_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='classschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.CharField(max_length=200)),
                ('todate', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('Staffallocation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.staff_allocation')),
            ],
        ),
    ]
