# Generated by Django 3.2.20 on 2023-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pdf',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
