# Generated by Django 3.2.20 on 2023-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.ImageField(null=True, upload_to='pdf/'),
        ),
    ]
