# Generated by Django 3.2.20 on 2023-10-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.CreateModel(
            name='File_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='image/')),
                ('TASK', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='myapp.task')),
            ],
        ),
    ]
